Select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(pruchase_amount) as revenue
from customer
group by gender

--Q2. Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, pruchase_amount
from customer
where discount_applied = 'Yes' and pruchase_amount >= (select AVG(pruchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, (AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5;

--Q4. Compare the average Purchase amounts between Standard and Express Shipping. 
Select shipping_type,
AVG(pruchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
Round(AVG(pruchase_amount),2)as avg_spend,
Round(SUM(pruchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased,
ROUND(100 * SUM(case when discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT (*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and loyal based on their total number of previous purchases, 
--show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 then 'New'
	WHEN previous_purchases between 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS Customer_segment
from customer
)

SELECT customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
SELECT age_group,
sum(pruchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC;

